name: env-fifa-21-dataset
channels:
  - defaults
dependencies:
  - atomicwrites=1.4.0
  - attrs=20.2.0
  - automat=20.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.9.3
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - colorama=0.4.4
  - constantly=15.1.0
  - cryptography=3.1.1
  - cssselect=1.1.0
  - hyperlink=20.0.1
  - idna=2.10
  - incremental=17.5.0
  - iniconfig=1.1.1
  - itemadapter=0.1.1
  - krb5=1.17.1
  - libiconv=1.15
  - libpq=12.2
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.6.1
  - more-itertools=8.5.0
  - openssl=1.1.1h
  - packaging=20.4
  - parsel=1.5.2
  - pip=20.2.4
  - pluggy=0.13.1
  - psycopg2=2.8.5
  - py=1.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pydispatcher=2.0.5
  - pyhamcrest=2.0.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.1.1
  - pytest-runner=5.2
  - python=3.8.0
  - pywin32=227
  - queuelib=1.5.0
  - requests=2.24.0
  - scrapy=2.4.0
  - service_identity=18.1.0
  - setuptools=50.3.0
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlalchemy=1.3.20
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - twisted=20.3.0
  - urllib3=1.25.11
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - w3lib=1.21.0
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=5.1.2
  - pip:
    - inflect==4.1.0
    - sqlacodegen==2.3.0
